### ISSUE TITLE
Download failed Mamp-Pro

### ISSUE THREAD

**Issue by forkmind** [matthewmueller/dots#12]
I've got this error 
<strong>curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'mamp' with message: Download failed: http://downloads.mamp.info/MAMP-PRO/releases/3.1/MAMP_MAMP_PRO_3.1.pkg</strong>
after downloading Mamp-Pro :
<strong>==> Downloading http://downloads.mamp.info/MAMP-PRO/releases/3.1/MAMP_MAMP_PRO_3.1.pkg</strong>

**Comment by facastagnini** [comment]
This should be closed, it is a cask bug not a dots bug.

More info: https://github.com/caskroom/homebrew-cask/pull/10557

**Comment by matthewmueller** [comment]
+1, unless they renamed it or something. We could also remove it.
